---
services:

  notes-server:
    build: .
    image: eedama2/notes-sever:latest
    container_name: ${NAMESPACE}_notes-sever
    env_file: .env
    restart: always
    ports:
    - 3000:3000
    depends_on:
    - mongodb
    volumes:
    - $PWD:/app:rw
    networks:
    - internal
    - web

  mongodb:
    image: webhippie/mongodb:latest
    container_name: ${NAMESPACE}_notes-mongodb
    restart: always
    ports:
    - 27017:27017
    - 28017:28017
    - 27019:27019
    volumes:
    - mongo-data:/var/lib/mongodb/db
    - mongo-backup:/var/lib/backup
    networks:
    - internal
    environment:
    - MONGODB_AUTH=${MONGODB_AUTH}
    - MONGODB_AUTH_DB=${MONGODB_AUTH_DB}
    - MONGODB_DATABASE=${MONGODB_DATABASE}
    - MONGODB_DBPATH=${MONGODB_DBPATH}
    - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    - MONGODB_REST=${MONGODB_REST}
    - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    - MONGODB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
    - MONGODB_USERNAME=${MONGODB_USERNAME}
    - MONGODB_VERBOSE=${MONGODB_VERBOSE}

  mongoexpress:
    restart: always
    image: mongo-express
    container_name: ${NAMESPACE}_kahoot-mongoexpress
    links:
    - mongodb:mongo
    environment:
    - VCAP_APP_PORT=8090
    - ME_CONFIG_MONGODB_AUTH_USERNAME=""
    - ME_CONFIG_MONGODB_AUTH_PASSWORD=""
    depends_on:
    - mongodb
    ports:
    - 8090:8090
    networks:
    - internal
    - web

networks:
  internal:
  web:
    external: true

volumes:
  mongo-data:
  mongo-backup:
    
